DROP TABLE IF EXISTS digitransit_operators;

CREATE TABLE digitransit_operators (
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

INSERT INTO digitransit_operators VALUES (1,   'Unknown');
INSERT INTO digitransit_operators VALUES (2,   'Unknown');
INSERT INTO digitransit_operators VALUES (3,   'Unknown');
INSERT INTO digitransit_operators VALUES (4,   'Unknown');
INSERT INTO digitransit_operators VALUES (5,   'Unknown');
INSERT INTO digitransit_operators VALUES (6,   'Unknown');
INSERT INTO digitransit_operators VALUES (7,   'Unknown');
INSERT INTO digitransit_operators VALUES (8,   'Unknown');
INSERT INTO digitransit_operators VALUES (9,   'Unknown');
INSERT INTO digitransit_operators VALUES (10,  'Unknown');
INSERT INTO digitransit_operators VALUES (11,  'Unknown');
INSERT INTO digitransit_operators VALUES (12,  'Helsingin Bussiliikenne Oy');
INSERT INTO digitransit_operators VALUES (13,  'Unknown');
INSERT INTO digitransit_operators VALUES (14,  'Unknown');
INSERT INTO digitransit_operators VALUES (15,  'Unknown');
INSERT INTO digitransit_operators VALUES (16,  'Unknown');
INSERT INTO digitransit_operators VALUES (17,  'Tammelundin Liikenne Oy');
INSERT INTO digitransit_operators VALUES (18,  'Oy Pohjolan Liikenne Ab');
INSERT INTO digitransit_operators VALUES (19,  'Unknown');
INSERT INTO digitransit_operators VALUES (20,  'Bus Travel Åbergin Linja Oy');
INSERT INTO digitransit_operators VALUES (21,  'Bus Travel Oy Reissu Ruoti');
INSERT INTO digitransit_operators VALUES (22,  'Nobina Finland Oy');
INSERT INTO digitransit_operators VALUES (23,  'Unknown');
INSERT INTO digitransit_operators VALUES (24,  'Unknown');
INSERT INTO digitransit_operators VALUES (25,  'Unknown');
INSERT INTO digitransit_operators VALUES (26,  'Unknown');
INSERT INTO digitransit_operators VALUES (27,  'Unknown');
INSERT INTO digitransit_operators VALUES (28,  'Unknown');
INSERT INTO digitransit_operators VALUES (29,  'Unknown');
INSERT INTO digitransit_operators VALUES (30,  'Savonlinja Oy');
INSERT INTO digitransit_operators VALUES (31,  'Unknown');
INSERT INTO digitransit_operators VALUES (32,  'Unknown');
INSERT INTO digitransit_operators VALUES (33,  'Unknown');
INSERT INTO digitransit_operators VALUES (34,  'Unknown');
INSERT INTO digitransit_operators VALUES (35,  'Unknown');
INSERT INTO digitransit_operators VALUES (36,  'Nurmijärven Linja Oy');
INSERT INTO digitransit_operators VALUES (37,  'Unknown');
INSERT INTO digitransit_operators VALUES (38,  'Unknown');
INSERT INTO digitransit_operators VALUES (39,  'Unknown');
INSERT INTO digitransit_operators VALUES (40,  'HKL-Raitioliikenne');
INSERT INTO digitransit_operators VALUES (41,  'Unknown');
INSERT INTO digitransit_operators VALUES (42,  'Unknown');
INSERT INTO digitransit_operators VALUES (43,  'Unknown');
INSERT INTO digitransit_operators VALUES (44,  'Unknown');
INSERT INTO digitransit_operators VALUES (45,  'Unknown');
INSERT INTO digitransit_operators VALUES (46,  'Unknown');
INSERT INTO digitransit_operators VALUES (47,  'Taksikuljetus Oy');
INSERT INTO digitransit_operators VALUES (48,  'Unknown');
INSERT INTO digitransit_operators VALUES (49,  'Unknown');
INSERT INTO digitransit_operators VALUES (50,  'HKL-Metroliikenne');
INSERT INTO digitransit_operators VALUES (51,  'Korsisaari Oy');
INSERT INTO digitransit_operators VALUES (52,  'Unknown');
INSERT INTO digitransit_operators VALUES (53,  'Unknown');
INSERT INTO digitransit_operators VALUES (54,  'V-S Bussipalvelut Oy');
INSERT INTO digitransit_operators VALUES (55,  'Unknown');
INSERT INTO digitransit_operators VALUES (56,  'Unknown');
INSERT INTO digitransit_operators VALUES (57,  'Unknown');
INSERT INTO digitransit_operators VALUES (58,  'Koillisen Liikennepalvelut Oy');
INSERT INTO digitransit_operators VALUES (59,  'Tilausliikenne Nikkanen Oy');
INSERT INTO digitransit_operators VALUES (60,  'Suomenlinnan Liikenne Oy');
INSERT INTO digitransit_operators VALUES (61,  'Unknown');
INSERT INTO digitransit_operators VALUES (62,  'Unknown');
INSERT INTO digitransit_operators VALUES (63,  'Unknown');
INSERT INTO digitransit_operators VALUES (64,  'Unknown');
INSERT INTO digitransit_operators VALUES (65,  'Unknown');
INSERT INTO digitransit_operators VALUES (66,  'Unknown');
INSERT INTO digitransit_operators VALUES (67,  'Unknown');
INSERT INTO digitransit_operators VALUES (68,  'Unknown');
INSERT INTO digitransit_operators VALUES (69,  'Unknown');
INSERT INTO digitransit_operators VALUES (70,  'Unknown');
INSERT INTO digitransit_operators VALUES (71,  'Unknown');
INSERT INTO digitransit_operators VALUES (72,  'Unknown');
INSERT INTO digitransit_operators VALUES (73,  'Unknown');
INSERT INTO digitransit_operators VALUES (74,  'Unknown');
INSERT INTO digitransit_operators VALUES (75,  'Unknown');
INSERT INTO digitransit_operators VALUES (76,  'Unknown');
INSERT INTO digitransit_operators VALUES (77,  'Unknown');
INSERT INTO digitransit_operators VALUES (78,  'Unknown');
INSERT INTO digitransit_operators VALUES (79,  'Unknown');
INSERT INTO digitransit_operators VALUES (80,  'Unknown');
INSERT INTO digitransit_operators VALUES (81,  'Unknown');
INSERT INTO digitransit_operators VALUES (82,  'Unknown');
INSERT INTO digitransit_operators VALUES (83,  'Unknown');
INSERT INTO digitransit_operators VALUES (84,  'Unknown');
INSERT INTO digitransit_operators VALUES (85,  'Unknown');
INSERT INTO digitransit_operators VALUES (86,  'Unknown');
INSERT INTO digitransit_operators VALUES (87,  'Unknown');
INSERT INTO digitransit_operators VALUES (88,  'Unknown');
INSERT INTO digitransit_operators VALUES (89,  'Metropolia');
INSERT INTO digitransit_operators VALUES (90,  'VR Oy');
INSERT INTO digitransit_operators VALUES (91,  'Unknown');
INSERT INTO digitransit_operators VALUES (92,  'Unknown');
INSERT INTO digitransit_operators VALUES (93,  'Unknown');
INSERT INTO digitransit_operators VALUES (94,  'Unknown');
INSERT INTO digitransit_operators VALUES (95,  'Unknown');
INSERT INTO digitransit_operators VALUES (96,  'Unknown');
INSERT INTO digitransit_operators VALUES (97,  'Unknown');
INSERT INTO digitransit_operators VALUES (98,  'Unknown');
INSERT INTO digitransit_operators VALUES (99,  'Unknown');
INSERT INTO digitransit_operators VALUES (100, 'Unknown');
INSERT INTO digitransit_operators VALUES (195, 'Siuntio1');
